version: "3"
services:
  database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=springproject
      - POSTGRES_USER=springproject_user
      - POSTGRES_PASSWORD=springproject_pass
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgressql/data
volumes:
  db-data:      
